[package]
name = "dmd_contract"
version = "0.0.1"
edition = "2018"

# keys and definitions: https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = "1"
solana-client = "1"
yaml-rust = "0.4"
thiserror = "1"
home = "0.5.3"
borsh = "0.9.1"
